name: router_impl
description: 'Implementation details of the Logger Module (go_router based)'
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.11.5
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^17.5.0
  router_api:
    git:
      url: https://github.com/Yusubov-Engineering/router.git
      path: router_api
      ref: v1.0.0
  material_ui: ^1.0.0
  dependency_injection_api:
    git:
      url: https://github.com/Yusubov-Engineering/dependency_injection.git
      path: dependency_injection_api
      ref: v1.0.0


dev_dependencies:
  app_linter:
    git:
      url: https://github.com/Yusubov-Engineering/app_linter.git
      path: .
      ref: v1.0.0
