name: router_impl
description: 'Implementation details of the Logger Module (go_router based)'
version: 1.0.0

resolution: workspace

environment:
  sdk: ^3.11.5
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^17.5.0
  router_api:
  material_ui:
  dependency_injection_api:

